project_id = "ehgnafsfgfgjadkzvvbh"

[functions.send-password-reset]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.resend-photographer-password-reset]
verify_jwt = true